### ISSUE TITLE
Can you update to support more types

### ISSUE THREAD

**Issue by yifan513** [muralivnv/small-cpp-matrix-library#1]
Can you update to support more types? 
Such as complex number, float and so on.

**Comment by muralivnv** [comment]
Hi. I wrote this header long time ago to experiment with OOP in C++ and now I see it violates a lot of design principles. 
In case you are not aware of Eigen, I would highly recommend you to checkout and use [Eigen](https://eigen.tuxfamily.org/index.php?title=Main_Page). 

Even though Eigen library takes a little bit of time to getting used (for complex vector/matrix manipulations), in the long-run it will pay-off.
